AMP-30409: Inconsistency in dash vs report data caused by difference …
devgateway/amp pull request #4013
Opened 2023-03-16 18:45 UTC by drychter

…in date range in global settings vs real dash. Reports were not displaying date property, setting start and end date to default

2023-03-16 19:08 UTC, jdeanquin-dg requested changes

2023-03-16 19:08 UTC, jdeanquin-dg commented on amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/filters-view.js
> +        debugger;
please remove the debugger from here

2023-03-16 19:20 UTC, drychter commented on amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/filters-view.js
> +        debugger;
good catch! done

2023-03-21 12:12 UTC, jdeanquin-dg submitted a review, later dismissed

2023-03-24 16:54 UTC, jdeanquin-dg approved these changes

2023-03-27 20:03 UTC, merged