AMP-30372: Documents permissions
devgateway/amp pull request #4019
Opened 2023-03-22 14:24 UTC by drychter

2023-03-24 16:49 UTC, jdeanquin-dg commented on amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/InterchangeEndpoints.java
> +        HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();
check this
AmpClientModeHolder.isOfflineClient()

2023-03-24 16:49 UTC, jdeanquin-dg requested changes
see my comment

2023-03-27 00:16 UTC, drychter commented on amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/InterchangeEndpoints.java
> +        HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();
done

2023-03-29 18:13 UTC, jdeanquin-dg submitted a review, later dismissed

2023-04-03 20:29 UTC, jdeanquin-dg approved these changes

2023-04-10 13:55 UTC, jdeanquin-dg approved these changes

2023-04-21 18:34 UTC, jdeanquin-dg approved these changes

2023-04-25 21:51 UTC, merged