AMP-30535 created patch to fix module visibility for parent
devgateway/amp pull request #4044
Opened 2023-05-04 17:59 UTC by timothygachengo

2023-05-04 18:27 UTC, jdeanquin-dg requested changes

2023-05-04 18:27 UTC, jdeanquin-dg commented on amp/.DS_Store
Please don't commit this file. Add it to .gitignore

2023-05-04 18:27 UTC, jdeanquin-dg commented on amp/deployConfigs/selected.properties
Please do not commit this file, so we don't generate conflicts with other branches

2023-05-04 18:27 UTC, jdeanquin-dg commented on amp/WEB-INF/src/org/digijava/module/aim/dbentity/AmpModulesVisibility.java
Even though the code committed is better, it's out of the scope of this change, so please revert.

2023-05-05 10:36 UTC, timothygachengo commented on amp/deployConfigs/selected.properties
Should I add this to the .gitignore?

2023-05-05 13:52 UTC, jdeanquin-dg requested changes

2023-05-05 13:52 UTC, jdeanquin-dg commented on amp/deployConfigs/selected.properties
you dont need to delete, you dont need to commit please revert the deletion and remove it from gitignore

2023-05-05 14:36 UTC, jdeanquin-dg submitted a review, later dismissed

2023-10-09 16:28 UTC, jdeanquin-dg commented
replaced by #4137

2023-10-09 16:28 UTC, closed without merging