Task/amp 30617/adjust activity preview multilingual
devgateway/amp pull request #4099
Opened 2023-08-28 14:18 UTC by drossi-dg

2023-08-29 13:53 UTC, jdeanquin-dg requested changes

2023-08-29 13:53 UTC, jdeanquin-dg commented on amp/TEMPLATE/reamp/modules/activity/preview/api/ActivityApi.jsx
> +        if (language != 'en') {
please remove this heck

2023-08-29 14:31 UTC, drossi-dg commented on amp/TEMPLATE/reamp/modules/activity/preview/api/ActivityApi.jsx
> +        if (language != 'en') {
done

2023-08-30 17:32 UTC, jdeanquin-dg approved these changes

2023-09-19 16:53 UTC, jdeanquin-dg approved these changes

2023-10-05 13:12 UTC, jdeanquin-dg approved these changes

2023-10-06 15:53 UTC, merged